//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP.App_UserControls.Fleet.FleetDetails.DayReport {
    
    
    public partial class FleetDayReport {
        
        /// <summary>
        /// UpdatePanelDayReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanelDayReport;
        
        /// <summary>
        /// LabelActiveFleetDayTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelActiveFleetDayTitle;
        
        /// <summary>
        /// ButtonCommandExport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Insight.App_UserControls.Controls.Commands.ButtonCommand ButtonCommandExport;
        
        /// <summary>
        /// ButtonCommandFilter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Insight.App_UserControls.Controls.Commands.ButtonCommand ButtonCommandFilter;
        
        /// <summary>
        /// ImageSeparator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image ImageSeparator;
        
        /// <summary>
        /// txtReportDayDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::APP.CustomControls.DateTextBox txtReportDayDate;
        
        /// <summary>
        /// imgreportdaydate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton imgreportdaydate;
        
        /// <summary>
        /// dtRDD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.CalendarExtender dtRDD;
        
        /// <summary>
        /// LabelHeaderFleetInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelHeaderFleetInformation;
        
        /// <summary>
        /// PlaceHolderData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder PlaceHolderData;
        
        /// <summary>
        /// ListViewFleetDayReportOverview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RAD.Controls.ListView ListViewFleetDayReportOverview;
        
        /// <summary>
        /// ListViewPager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RAD.Controls.ListViewPager ListViewPager;
        
        /// <summary>
        /// PlaceHolderNoData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder PlaceHolderNoData;
        
        /// <summary>
        /// UCEmptyData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::APP.App_UserControls.Controls.EmptyDataTemplate UCEmptyData;
    }
}
