CREATE TABLE [dbo].[Archive.ManualInvoice] (
    [RowId]            INT            IDENTITY (1, 1) NOT NULL,
    [CountryName]      VARCHAR (100)  NULL,
    [CompanyName]      VARCHAR (255)  NULL,
    [DocumentType]     VARCHAR (50)   NULL,
    [InvoiceType]      VARCHAR (50)   NULL,
    [InvoiceDate]      DATETIME       NULL,
    [BuyerName]        VARCHAR (255)  NULL,
    [BuyerCode]        VARCHAR (255)  NULL,
    [Serial]           VARCHAR (50)   NULL,
    [Amount]           MONEY          NULL,
    [TaxCode]          VARCHAR (50)   NULL,
    [DescriptionName]  VARCHAR (2000) NULL,
    [CompanyId]        INT            NULL,
    [CountryId]        INT            NULL,
    [TaxCodeId]        INT            NULL,
    [DocumentTypeId]   INT            NULL,
    [ContactTypeId]    INT            NULL,
    [VehicleId]        INT            NULL,
    [ModelCodeId]      INT            NULL,
    [ModelId]          INT            NULL,
    [ModelDetailId]    INT            NULL,
    [BuyerId]          INT            NULL,
    [ManufacturerName] VARCHAR (100)  NULL,
    [ManufacturerId]   INT            NULL,
    [DocumentId]       INT            NULL,
    [ItemId]           INT            NULL,
    [DocItemId]        INT            NULL,
    [BuyerAddressId]   INT            NULL,
    [BuyerAddress1]    VARCHAR (500)  NULL,
    [BuyerAddress2]    VARCHAR (500)  NULL,
    [BuyerAddress3]    VARCHAR (500)  NULL,
    [BuyerAddress4]    VARCHAR (500)  NULL,
    [BuyerFiscalCode]  VARCHAR (100)  NULL,
    [ManufacturerCode] VARCHAR (10)   NULL,
    [InvoiceNumber]    VARCHAR (50)   NULL,
    [ExtrasId]         INT            NULL,
    [InvoiceNet]       FLOAT (53)     NULL,
    [InvoiceVat]       FLOAT (53)     NULL,
    [InvoiceTotal]     FLOAT (53)     NULL,
    [VatPCT]           FLOAT (53)     NULL,
    PRIMARY KEY CLUSTERED ([RowId] ASC)
);

