CREATE TABLE [dbo].[Fact.FleetTaxReport] (
    [RowId]              INT           IDENTITY (1, 1) NOT NULL,
    [CompanyId]          INT           NULL,
    [Serial]             VARCHAR (50)  NULL,
    [Plate]              VARCHAR (20)  NULL,
    [Unit]               VARCHAR (20)  NULL,
    [ManufacturerId]     INT           NULL,
    [ModelDetailId]      INT           NULL,
    [RegTaxAmount]       FLOAT (53)    NULL,
    [InvoiceNumber]      VARCHAR (50)  NULL,
    [BuyerId]            INT           NULL,
    [VehicleId]          INT           NULL,
    [LogId]              INT           NULL,
    [NRCDate]            DATETIME      NULL,
    [Processed]          BIT           NULL,
    [TaxDate]            DATETIME      NULL,
    [InvoiceDate]        DATETIME      NULL,
    [FileDate]           DATETIME      NULL,
    [Mileage]            VARCHAR (20)  NULL,
    [InvoiceNet]         VARCHAR (20)  NULL,
    [BankRegCode]        VARCHAR (100) NULL,
    [CO2]                VARCHAR (20)  NULL,
    [ManufacturerName]   VARCHAR (100) NULL,
    [ITVSerial]          VARCHAR (100) NULL,
    [MSODate]            DATETIME      NULL,
    [FuelType]           VARCHAR (20)  NULL,
    [TaxCode]            VARCHAR (20)  NULL,
    [TaxPCT]             VARCHAR (20)  NULL,
    [SaleDocumentNumber] VARCHAR (100) NULL,
    [SaleDate]           DATETIME      NULL,
    [VehicleCode]        VARCHAR (10)  NULL,
    [EngineSize]         VARCHAR (20)  NULL,
    [IsCorrect]          BIT           NULL,
    [IsExported]         BIT           NULL,
    PRIMARY KEY CLUSTERED ([RowId] ASC)
);

