CREATE TABLE [dbo].[GESLE_His] (
    [sleHisid]                 INT           NOT NULL,
    [Serial]                   VARCHAR (20)  NULL,
    [LAST8]                    VARCHAR (20)  NULL,
    [Unit]                     VARCHAR (20)  NULL,
    [ModelCode]                VARCHAR (20)  NULL,
    [ModelDescription]         VARCHAR (255) NULL,
    [Plate]                    VARCHAR (50)  NULL,
    [ContrType]                VARCHAR (10)  NULL,
    [Mileage]                  INT           NULL,
    [VehType]                  VARCHAR (50)  NULL,
    [UnfallWa_JN]              INT           NULL,
    [TbcNr]                    INT           NULL,
    [StationCode]              VARCHAR (20)  NULL,
    [TdfNr]                    VARCHAR (50)  NULL,
    [StationOutDate]           DATETIME      NULL,
    [LeaseRefDate]             DATETIME      NULL,
    [AbgabedatumRG]            DATETIME      NULL,
    [BlockSysDate]             DATETIME      NULL,
    [AbgabeTransport]          DATETIME      NULL,
    [DistriOut]                DATETIME      NULL,
    [RegDate]                  DATETIME      NULL,
    [SaleRefDate]              DATETIME      NULL,
    [Haendler]                 VARCHAR (100) NULL,
    [BuyerCode]                INT           NOT NULL,
    [BuyerCode2]               INT           NULL,
    [AnlAccCode]               VARCHAR (20)  NULL,
    [MBDieselstr]              DATETIME      NULL,
    [FleetAdminFlaccDeActDate] DATETIME      NULL,
    [DocumentNr]               INT           NULL,
    [ReceiptDate]              DATETIME      NULL,
    [VisionOut]                DATETIME      NULL,
    [InvoiceNet]               MONEY         NULL,
    [InvoiceVat]               MONEY         NULL,
    [InvoiceTotal]             MONEY         NULL,
    [Vertrag_JN]               BIT           NULL,
    [Brief_JN]                 BIT           NULL,
    [PayTerm]                  INT           NULL,
    [UstID]                    VARCHAR (20)  NULL,
    [InvoiceNumber]            INT           NOT NULL,
    [InvoiceDate]              DATETIME      NULL,
    [ReStorno]                 BIT           NULL,
    [Recondition]              FLOAT (53)    NULL,
    [Paid]                     BIT           NULL,
    [reminder1]                DATETIME      NULL,
    [reminder2]                DATETIME      NULL,
    [RemStop]                  BIT           NULL,
    [HER_Code]                 VARCHAR (20)  NULL,
    [DataSource]               VARCHAR (5)   NULL,
    [copies]                   TINYINT       NULL,
    [PBrutto]                  FLOAT (53)    NULL,
    [PBMerker]                 BIT           NULL,
    [HBriefStatus]             BIT           NULL,
    [CapitalCost]              FLOAT (53)    NULL,
    [Depreciation]             FLOAT (53)    NULL,
    [Recond2]                  FLOAT (53)    NULL,
    [Mile_Charge]              FLOAT (53)    NULL,
    [Other1]                   FLOAT (53)    NULL,
    [Other2]                   FLOAT (53)    NULL,
    [InServiceDate]            DATETIME      NULL,
    [OutServiceDate]           DATETIME      NULL,
    [MSODate]                  DATETIME      NULL,
    [DB_SV]                    FLOAT (53)    NULL,
    [BriefAnfDatum]            DATETIME      NULL,
    [DDays]                    INT           NULL,
    [invType]                  VARCHAR (2)   NULL,
    [amount1]                  MONEY         NULL,
    [amount2]                  MONEY         NULL,
    [amount3]                  MONEY         NULL,
    [amount4]                  MONEY         NULL,
    [amount5]                  MONEY         NULL,
    [amount6]                  MONEY         NULL,
    [amount7]                  MONEY         NULL
);

