CREATE TABLE [dbo].[Migration.Italy] (
    [RowId]              INT           IDENTITY (1, 1) NOT NULL,
    [CompanyCode]        VARCHAR (20)  NULL,
    [AreaCode]           VARCHAR (20)  NULL,
    [Serial]             VARCHAR (50)  NULL,
    [Unit]               VARCHAR (20)  NULL,
    [Plate]              VARCHAR (20)  NULL,
    [Mileage]            VARCHAR (20)  NULL,
    [InServiceDate]      DATETIME      NULL,
    [OutServiceDate]     DATETIME      NULL,
    [MSODate]            DATETIME      NULL,
    [ModelCode]          VARCHAR (30)  NULL,
    [ModelDescription]   VARCHAR (255) NULL,
    [CarColor]           VARCHAR (20)  NULL,
    [ModelYear]          VARCHAR (20)  NULL,
    [ManufacturerCode]   VARCHAR (20)  NULL,
    [ManufacturerName]   VARCHAR (255) NULL,
    [VehicleClass]       VARCHAR (20)  NULL,
    [VehicleType]        VARCHAR (20)  NULL,
    [PurchaseOrder]      VARCHAR (30)  NULL,
    [PayDate]            DATETIME      NULL,
    [InvoiceNumber]      VARCHAR (50)  NULL,
    [SaleDate]           DATETIME      NULL,
    [InvoiceDate]        DATETIME      NULL,
    [SaleType]           VARCHAR (20)  NULL,
    [SaleDocumentNumber] VARCHAR (50)  NULL,
    [InvoiceNet]         FLOAT (53)    NULL,
    [InvoiceVat]         FLOAT (53)    NULL,
    [InvoiceTotal]       FLOAT (53)    NULL,
    [BuyerCode]          VARCHAR (50)  NULL,
    [BuyerName]          VARCHAR (255) NULL,
    [BuyerAddress1]      VARCHAR (255) NULL,
    [BuyerAddress2]      VARCHAR (255) NULL,
    [BuyerAddress3]      VARCHAR (255) NULL,
    [BuyerAddress4]      VARCHAR (255) NULL,
    [BuyerFiscalCode]    VARCHAR (50)  NULL,
    [CapitalCost]        FLOAT (53)    NULL,
    [Depreciation]       FLOAT (53)    NULL,
    [BookValue]          FLOAT (53)    NULL,
    [BuyBackCap]         FLOAT (53)    NULL,
    [MileCharge]         FLOAT (53)    NULL,
    [PlusKM]             FLOAT (53)    NULL,
    [FuelCharge]         FLOAT (53)    NULL,
    [Damage]             FLOAT (53)    NULL,
    [TransferFees]       FLOAT (53)    NULL,
    [TransferFeesNoVat]  FLOAT (53)    NULL,
    [TaxDescription1]    VARCHAR (50)  NULL,
    [TaxDescription2]    VARCHAR (50)  NULL,
    [TaxDescription3]    VARCHAR (50)  NULL,
    [OriginalBPM]        FLOAT (53)    NULL,
    [CalcVatAmortized]   FLOAT (53)    NULL,
    [Unamortized]        FLOAT (53)    NULL,
    [SuperCharge]        FLOAT (53)    NULL,
    [HandleFee]          FLOAT (53)    NULL,
    [AddOn]              FLOAT (53)    NULL,
    [Other1]             FLOAT (53)    NULL,
    [Other2]             FLOAT (53)    NULL,
    [Amount5]            FLOAT (53)    NULL,
    [Amount6]            FLOAT (53)    NULL,
    [Amount7]            VARCHAR (200) NULL,
    [ExportTo]           VARCHAR (50)  NULL,
    [Tax]                VARCHAR (20)  NULL,
    [RegTaxAmount]       FLOAT (53)    NULL,
    [VehicleId]          INT           NULL,
    [ItemId]             INT           NULL,
    [DocumentId]         INT           NULL,
    [LogId]              INT           NULL,
    [IsRepeated]         BIT           NULL,
    [IsDuplicate]        BIT           NULL,
    [Notes]              VARCHAR (255) NULL,
    [BuyerId]            INT           NULL,
    [ModelId]            INT           NULL,
    [CountryId]          INT           NULL,
    [HasBuyer]           BIT           NULL,
    [HasModel]           BIT           NULL,
    [CompanyId]          INT           NULL,
    [ExtrasId]           INT           NULL,
    [ModelDetailId]      INT           NULL,
    [ModelCodeId]        INT           NULL,
    [DocumentTypeId]     INT           NULL,
    [ContactTypeId]      INT           NULL,
    [HasDocument]        BIT           NULL,
    [DocItemId]          INT           NULL,
    [OldRowId]           INT           NULL,
    [OldInvoiceNumber]   VARCHAR (50)  NULL,
    [OldInvoiceDate]     DATETIME      NULL,
    [IsError]            BIT           NULL,
    [IsReport]           BIT           NULL,
    [TaxCodeId]          INT           NULL,
    [BuyerAddressId]     INT           NULL,
    [NoInvoiceDate]      BIT           NULL,
    [NoInvoiceNumber]    BIT           NULL,
    [NoBuyerCode]        BIT           NULL,
    [NoModelCode]        BIT           NULL,
    CONSTRAINT [v] PRIMARY KEY CLUSTERED ([RowId] ASC)
);

