CREATE TABLE [dbo].[Staging.Dashboard] (
    [RowId]              INT            IDENTITY (1, 1) NOT NULL,
    [SaleDocumentNumber] VARCHAR (50)   NULL,
    [InvoiceDate]        DATETIME       NULL,
    [Serial]             VARCHAR (50)   NULL,
    [AreaCode]           VARCHAR (20)   NULL,
    [CompanyCode]        VARCHAR (20)   NULL,
    [RecvType]           VARCHAR (20)   NULL,
    [ManufacturerName]   VARCHAR (255)  NULL,
    [VehicleStatus]      VARCHAR (20)   NULL,
    [OMU]                VARCHAR (20)   NULL,
    [RMSAge]             VARCHAR (20)   NULL,
    [RecvAmt]            FLOAT (53)     NULL,
    [OutServiceDate]     DATETIME       NULL,
    [Plate]              VARCHAR (50)   NULL,
    [InServiceDate]      DATETIME       NULL,
    [PurchaseOrder]      VARCHAR (50)   NULL,
    [PurchInvoiceNumber] VARCHAR (50)   NULL,
    [CapitalCost]        FLOAT (53)     NULL,
    [Depreciation]       FLOAT (53)     NULL,
    [NetRecv]            FLOAT (53)     NULL,
    [RecvDueInd]         VARCHAR (20)   NULL,
    [RecvDueDate]        DATETIME       NULL,
    [InvoiceNbr]         VARCHAR (50)   NULL,
    [VehicleType]        VARCHAR (20)   NULL,
    [SPI]                VARCHAR (50)   NULL,
    [ModelCodeVision]    VARCHAR (50)   NULL,
    [DueDtAge]           VARCHAR (20)   NULL,
    [ClaimDate]          DATETIME       NULL,
    [Unit]               VARCHAR (50)   NULL,
    [InvoiceNumber]      VARCHAR (50)   NULL,
    [CountryId]          INT            NULL,
    [CompanyId]          INT            NULL,
    [ModelCodeId]        INT            NULL,
    [ModelId]            INT            NULL,
    [ModelDetailId]      INT            NULL,
    [ManufacturerId]     INT            NULL,
    [VehicleId]          INT            NULL,
    [BuyerId]            INT            NULL,
    [RecvTypeId]         INT            NULL,
    [ItemId]             INT            NULL,
    [DocumentId]         INT            NULL,
    [DocItemId]          INT            NULL,
    [Notes]              VARCHAR (2000) NULL,
    [FileId]             INT            NULL,
    [LogId]              INT            NULL,
    [GroupId]            INT            NULL,
    PRIMARY KEY CLUSTERED ([RowId] ASC)
);

