-- =============================================
-- Author:		Javier
-- Create date: October 2011
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[spDBImportActiveFleetTransactionsUpload]
		@fileId		VARCHAR(1),
		@CompanyCode VARCHAR(20) = NULL,
		@AreaCode VARCHAR(50) = NULL,
		@Serial VARCHAR(20) = NULL,
		@Unit VARCHAR(20) = NULL,
		@TasModel VARCHAR(20) = NULL,
		@ModelCode VARCHAR(30) = NULL,
		@ManufacturerName VARCHAR(255) = NULL,
		@ModelGroup VARCHAR(20) = NULL,
		@ModelDescription VARCHAR(255) = NULL,
		@RateClass VARCHAR(20) = NULL,
		@VehicleType VARCHAR(20) = NULL,
		@CapitalCost VARCHAR(20) = NULL,
		@Depreciation VARCHAR(20) = NULL,
		@DepreciationRate VARCHAR(20) = NULL,
		@DepreciationPCT VARCHAR(20) = NULL,
		@BookValue VARCHAR(20) = NULL,
		@DeliveryDate VARCHAR(20) = NULL,
		@MSODate VARCHAR(20) = NULL,
		@InServiceDate VARCHAR(20) = NULL,
		@OutServiceDate VARCHAR(20) = NULL,
		@DaysInService VARCHAR(20) = NULL,
		@SalePrice VARCHAR(20) = NULL,
		@Mileage VARCHAR(20) = NULL,
		@AdjReceivable VARCHAR(20) = NULL,
		@ReceivableType VARCHAR(20) = NULL,
		@AmortizedID VARCHAR(20) = NULL,
		@FirstRA VARCHAR(20) = NULL,
		@RADate VARCHAR(20) = NULL,
		@SaleType VARCHAR(20) = NULL,
		@VehicleStatus VARCHAR(20) = NULL,
		@Plate VARCHAR(20) = NULL,
		@SaleDate VARCHAR(20) = NULL,
		@VehicleClass VARCHAR(20) = NULL,
		@DeliveryDate_2 VARCHAR(20) = NULL,
		@OutServiceDate_2 VARCHAR(20) = NULL,
		@ModelYear VARCHAR(20) = NULL,
		@CapitalCostFleetco VARCHAR(50) = NULL
	
AS
BEGIN

	SET NOCOUNT ON;

	IF @fileId = '3'
	BEGIN
		INSERT INTO [Import.ActiveFleetMonthAdds] 
		(
			CompanyCode,
			AreaCode,
			Serial,
			Unit,
			TasModel,
			ModelCode,
			ManufacturerName,
			ModelGroup,
			ModelDescription,
			RateClass,
			VehicleType,
			CapitalCost,
			Depreciation,
			DepreciationRate,
			DepreciationPCT,
			BookValue,
			DeliveryDate,
			MSODate,
			InServiceDate,
			OutServiceDate,
			DaysInService,
			SalePrice,
			Mileage,
			AdjReceivable,
			ReceivableType,
			AmortizedID,
			FirstRA,
			RADate,
			SaleType,
			VehicleStatus,
			Plate,
			SaleDate,
			VehicleClass,
			DeliveryDate_2,
			OutServiceDate_2,
			ModelYear,
			CapitalCostFleetco
		
		)
		VALUES
		(
			@CompanyCode,
			@AreaCode,
			@Serial,
			@Unit,
			@TasModel,
			@ModelCode,
			@ManufacturerName,
			@ModelGroup,
			@ModelDescription,
			@RateClass,
			@VehicleType,
			@CapitalCost,
			@Depreciation,
			@DepreciationRate,
			@DepreciationPCT,
			@BookValue,
			@DeliveryDate,
			@MSODate,
			@InServiceDate,
			@OutServiceDate,
			@DaysInService,
			@SalePrice,
			@Mileage,
			@AdjReceivable,
			@ReceivableType,
			@AmortizedID,
			@FirstRA,
			@RADate,
			@SaleType,
			@VehicleStatus,
			@Plate,
			@SaleDate,
			@VehicleClass,
			@DeliveryDate_2,
			@OutServiceDate_2,
			@ModelYear,
			@CapitalCostFleetco
		
		)
	END
	ELSE IF @fileId = '4'
	BEGIN
		INSERT INTO [Import.ActiveFleetMonthDels]
		(
			CompanyCode,
			AreaCode,
			Serial,
			Unit,
			TasModel,
			ModelCode,
			ManufacturerName,
			ModelGroup,
			ModelDescription,
			RateClass,
			VehicleType,
			CapitalCost,
			Depreciation,
			DepreciationRate,
			DepreciationPCT,
			BookValue,
			DeliveryDate,
			MSODate,
			InServiceDate,
			OutServiceDate,
			DaysInService,
			SalePrice,
			Mileage,
			AdjReceivable,
			ReceivableType,
			AmortizedID,
			FirstRA,
			RADate,
			SaleType,
			VehicleStatus,
			Plate,
			SaleDate,
			VehicleClass,
			DeliveryDate_2,
			OutServiceDate_2,
			ModelYear,
			CapitalCostFleetco
		)
		VALUES
		(
			@CompanyCode,
			@AreaCode,
			@Serial,
			@Unit,
			@TasModel,
			@ModelCode,
			@ManufacturerName,
			@ModelGroup,
			@ModelDescription,
			@RateClass,
			@VehicleType,
			@CapitalCost,
			@Depreciation,
			@DepreciationRate,
			@DepreciationPCT,
			@BookValue,
			@DeliveryDate,
			@MSODate,
			@InServiceDate,
			@OutServiceDate,
			@DaysInService,
			@SalePrice,
			@Mileage,
			@AdjReceivable,
			@ReceivableType,
			@AmortizedID,
			@FirstRA,
			@RADate,
			@SaleType,
			@VehicleStatus,
			@Plate,
			@SaleDate,
			@VehicleClass,
			@DeliveryDate_2,
			@OutServiceDate_2,
			@ModelYear,
			@CapitalCostFleetco
		
		)
	END
	ELSE IF @fileId = '5'
	BEGIN
		INSERT INTO [Import.ActiveFleetYearAdds]
		(
			CompanyCode,
			AreaCode,
			Serial,
			Unit,
			TasModel,
			ModelCode,
			ManufacturerName,
			ModelGroup,
			ModelDescription,
			RateClass,
			VehicleType,
			CapitalCost,
			Depreciation,
			DepreciationRate,
			DepreciationPCT,
			BookValue,
			DeliveryDate,
			MSODate,
			InServiceDate,
			OutServiceDate,
			DaysInService,
			SalePrice,
			Mileage,
			AdjReceivable,
			ReceivableType,
			AmortizedID,
			FirstRA,
			RADate,
			SaleType,
			VehicleStatus,
			Plate,
			SaleDate,
			VehicleClass,
			DeliveryDate_2,
			OutServiceDate_2,
			ModelYear,
			CapitalCostFleetco
		)
		VALUES
		(
			@CompanyCode,
			@AreaCode,
			@Serial,
			@Unit,
			@TasModel,
			@ModelCode,
			@ManufacturerName,
			@ModelGroup,
			@ModelDescription,
			@RateClass,
			@VehicleType,
			@CapitalCost,
			@Depreciation,
			@DepreciationRate,
			@DepreciationPCT,
			@BookValue,
			@DeliveryDate,
			@MSODate,
			@InServiceDate,
			@OutServiceDate,
			@DaysInService,
			@SalePrice,
			@Mileage,
			@AdjReceivable,
			@ReceivableType,
			@AmortizedID,
			@FirstRA,
			@RADate,
			@SaleType,
			@VehicleStatus,
			@Plate,
			@SaleDate,
			@VehicleClass,
			@DeliveryDate_2,
			@OutServiceDate_2,
			@ModelYear,
			@CapitalCostFleetco
		
		)
	END
	ELSE IF @fileId = '6'
	BEGIN
		INSERT INTO [Import.ActiveFleetYearDels]
		(
			CompanyCode,
			AreaCode,
			Serial,
			Unit,
			TasModel,
			ModelCode,
			ManufacturerName,
			ModelGroup,
			ModelDescription,
			RateClass,
			VehicleType,
			CapitalCost,
			Depreciation,
			DepreciationRate,
			DepreciationPCT,
			BookValue,
			DeliveryDate,
			MSODate,
			InServiceDate,
			OutServiceDate,
			DaysInService,
			SalePrice,
			Mileage,
			AdjReceivable,
			ReceivableType,
			AmortizedID,
			FirstRA,
			RADate,
			SaleType,
			VehicleStatus,
			Plate,
			SaleDate,
			VehicleClass,
			DeliveryDate_2,
			OutServiceDate_2,
			ModelYear,
			CapitalCostFleetco
		)
		VALUES
		(
			@CompanyCode,
			@AreaCode,
			@Serial,
			@Unit,
			@TasModel,
			@ModelCode,
			@ManufacturerName,
			@ModelGroup,
			@ModelDescription,
			@RateClass,
			@VehicleType,
			@CapitalCost,
			@Depreciation,
			@DepreciationRate,
			@DepreciationPCT,
			@BookValue,
			@DeliveryDate,
			@MSODate,
			@InServiceDate,
			@OutServiceDate,
			@DaysInService,
			@SalePrice,
			@Mileage,
			@AdjReceivable,
			@ReceivableType,
			@AmortizedID,
			@FirstRA,
			@RADate,
			@SaleType,
			@VehicleStatus,
			@Plate,
			@SaleDate,
			@VehicleClass,
			@DeliveryDate_2,
			@OutServiceDate_2,
			@ModelYear,
			@CapitalCostFleetco
		
		)
	END
   
END