-- =============================================
-- Author:		Javier
-- Create date: October 2011
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[spDBImportSalesUpload]
		@CompanyCode VARCHAR(20) = NULL,
		@AreaCode VARCHAR(20) = NULL,
		@Serial VARCHAR(50) = NULL,
		@Unit VARCHAR(20) = NULL,
		@Plate VARCHAR(20) = NULL,
		@Mileage VARCHAR(20) = NULL,
		@InServiceDate VARCHAR(20) = NULL,
		@OutServiceDate VARCHAR(20) = NULL,
		@MSODate VARCHAR(20) = NULL,
		@ModelCode VARCHAR(30) = NULL,
		@ModelDescription VARCHAR(255) = NULL,
		@CarColor VARCHAR(20) = NULL,
		@ModelYear VARCHAR(20) = NULL,
		@ManufacturerCode VARCHAR(20) = NULL,
		@ManufacturerName VARCHAR(255) = NULL,
		@VehicleClass VARCHAR(20) = NULL,
		@VehicleType VARCHAR(20) = NULL,
		@PurchaseOrder VARCHAR(30) = NULL,
		@PayDate VARCHAR(20) = NULL,
		@InvoiceNumber VARCHAR(50) = NULL,
		@SaleDate VARCHAR(20) = NULL,
		@InvoiceDate VARCHAR(50) = NULL,
		@SaleType VARCHAR(10) = NULL,
		@SaleDocumentNumber VARCHAR(50) = NULL,
		@InvoiceNet VARCHAR(20) = NULL,
		@InvoiceVat VARCHAR(20) = NULL,
		@InvoiceTotal VARCHAR(20) = NULL,
		@BuyerCode VARCHAR(50) = NULL,
		@BuyerName VARCHAR(255) = NULL,
		@BuyerAddress1 VARCHAR(255) = NULL,
		@BuyerAddress2 VARCHAR(255) = NULL,
		@BuyerAddress3 VARCHAR(255) = NULL,
		@BuyerAddress4 VARCHAR(255) = NULL,
		@BuyerFiscalCode VARCHAR(50) = NULL,
		@CapitalCost VARCHAR(20) = NULL,
		@Depreciation VARCHAR(20) = NULL,
		@BookValue VARCHAR(20) = NULL,
		@BuyBackCap VARCHAR(20) = NULL,
		@MileCharge VARCHAR(20) = NULL,
		@PlusKM VARCHAR(20) = NULL,
		@FuelCharge VARCHAR(20) = NULL,
		@Damage VARCHAR(20) = NULL,
		@TransferFees VARCHAR(20) = NULL,
		@TransferFeesNoVat VARCHAR(20) = NULL,
		@TaxDescription1 VARCHAR(50) = NULL,
		@TaxDescription2 VARCHAR(50) = NULL,
		@TaxDescription3 VARCHAR(50) = NULL,
		@OriginalBPM VARCHAR(20) = NULL,
		@CalcVatAmortized VARCHAR(20) = NULL,
		@Unamortized VARCHAR(20) = NULL,
		@SuperCharge VARCHAR(20) = NULL,
		@HandleFee VARCHAR(20) = NULL,
		@AddOn VARCHAR(20) = NULL,
		@Other1 VARCHAR(20) = NULL,
		@Other2 VARCHAR(20) = NULL,
		@Amount5 VARCHAR(20) = NULL,
		@Amount6 VARCHAR(20) = NULL,
		@Amount7 VARCHAR(20) = NULL,
		@ExportTo VARCHAR(50) = NULL,
		@Tax VARCHAR(20) = NULL,
		@RegTaxAmount VARCHAR(20) = NULL

AS
BEGIN
	
	SET NOCOUNT ON;
	
	INSERT INTO [Import.SalesOR]
	(
		CompanyCode,
		AreaCode,
		Serial,
		Unit,
		Plate,
		Mileage,
		InServiceDate,
		OutServiceDate,
		MSODate,
		ModelCode,
		ModelDescription,
		CarColor,
		ModelYear,
		ManufacturerCode,
		ManufacturerName,
		VehicleClass,
		VehicleType,
		PurchaseOrder,
		PayDate,
		InvoiceNumber,
		SaleDate,
		InvoiceDate,
		SaleType,
		SaleDocumentNumber,
		InvoiceNet,
		InvoiceVat,
		InvoiceTotal,
		BuyerCode,
		BuyerName,
		BuyerAddress1,
		BuyerAddress2,
		BuyerAddress3,
		BuyerAddress4,
		BuyerFiscalCode,
		CapitalCost,
		Depreciation,
		BookValue,
		BuyBackCap,
		MileCharge,
		PlusKM,
		FuelCharge,
		Damage,
		TransferFees,
		TransferFeesNoVat,
		TaxDescription1,
		TaxDescription2,
		TaxDescription3,
		OriginalBPM,
		CalcVatAmortized,
		Unamortized,
		SuperCharge,
		HandleFee,
		AddOn,
		Other1,
		Other2,
		Amount5,
		Amount6,
		Amount7,
		ExportTo,
		Tax,
		RegTaxAmount
	)
	VALUES
	(
		@CompanyCode,
		@AreaCode,
		@Serial,
		@Unit,
		@Plate,
		@Mileage,
		@InServiceDate,
		@OutServiceDate,
		@MSODate,
		@ModelCode,
		@ModelDescription,
		@CarColor,
		@ModelYear,
		@ManufacturerCode,
		@ManufacturerName,
		@VehicleClass,
		@VehicleType,
		@PurchaseOrder,
		@PayDate,
		@InvoiceNumber,
		@SaleDate,
		@InvoiceDate,
		@SaleType,
		@SaleDocumentNumber,
		@InvoiceNet,
		@InvoiceVat,
		@InvoiceTotal,
		@BuyerCode,
		@BuyerName,
		@BuyerAddress1,
		@BuyerAddress2,
		@BuyerAddress3,
		@BuyerAddress4,
		@BuyerFiscalCode,
		@CapitalCost,
		@Depreciation,
		@BookValue,
		@BuyBackCap,
		@MileCharge,
		@PlusKM,
		@FuelCharge,
		@Damage,
		@TransferFees,
		@TransferFeesNoVat,
		@TaxDescription1,
		@TaxDescription2,
		@TaxDescription3,
		@OriginalBPM,
		@CalcVatAmortized,
		@Unamortized,
		@SuperCharge,
		@HandleFee,
		@AddOn,
		@Other1,
		@Other2,
		@Amount5,
		@Amount6,
		@Amount7,
		@ExportTo,
		@Tax,
		@RegTaxAmount
	)

    
END