CREATE TABLE [dbo].[GEModels2] (
    [DEL]        NVARCHAR (1)  NULL,
    [MODCODE]    NVARCHAR (4)  NULL,
    [MODELL]     NVARCHAR (10) NULL,
    [MODBEZ1]    NVARCHAR (9)  NULL,
    [MODBEZ2]    NVARCHAR (16) NULL,
    [HER_CODE]   NVARCHAR (2)  NULL,
    [GRUPPE]     NVARCHAR (2)  NULL,
    [H_FRIST]    FLOAT (53)    NULL,
    [SCHALTART]  NVARCHAR (1)  NULL,
    [TELEFON]    NVARCHAR (1)  NULL,
    [AKTIV]      NVARCHAR (1)  NULL,
    [STATUS]     NVARCHAR (2)  NULL,
    [STATUS2]    NVARCHAR (3)  NULL,
    [AUFNAHME_C] NVARCHAR (2)  NULL,
    [HUBRAUM]    FLOAT (53)    NULL,
    [OTTO_DIES]  NVARCHAR (1)  NULL,
    [CAR_VAN]    NVARCHAR (2)  NULL,
    [MODBEZ3]    NVARCHAR (54) NULL
);

