CREATE TABLE [dbo].[GEModels] (
    [ModelCode]          VARCHAR (4)   NOT NULL,
    [cModCodeWT]         VARCHAR (4)   NOT NULL,
    [cReplacedBy]        VARCHAR (4)   NULL,
    [ModelDescription]   VARCHAR (70)  NULL,
    [TasCode]            VARCHAR (16)  NULL,
    [cModGroup]          VARCHAR (20)  NULL,
    [cClass]             VARCHAR (2)   NULL,
    [ManCode]            INT           NULL,
    [ModLineCode]        INT           NULL,
    [ModLineClusterCode] INT           NULL,
    [cModDescriptionPo]  VARCHAR (80)  NULL,
    [BodyTypeCode]       INT           NULL,
    [Doors]              TINYINT       NULL,
    [Seats]              TINYINT       NULL,
    [cGearBox]           VARCHAR (1)   NULL,
    [Gears]              TINYINT       NULL,
    [cFuelTypeCode]      VARCHAR (2)   NULL,
    [CubicCap]           INT           NULL,
    [Hp]                 SMALLINT      NULL,
    [KW]                 SMALLINT      NULL,
    [cCarGroup]          VARCHAR (2)   NULL,
    [cComment1]          VARCHAR (250) NULL,
    [cComment2]          VARCHAR (250) NULL,
    [Ahk]                BIT           NULL,
    [Nav]                BIT           NULL,
    [IdleWeight]         INT           NULL,
    [GrossWeight]        INT           NULL,
    [Cylinder]           TINYINT       NULL,
    [ConsumptionLpKm]    REAL          NULL,
    [TankCapacity]       SMALLINT      NULL,
    [LuggageCapacity]    INT           NULL,
    [cWheelDrive]        VARCHAR (50)  NULL,
    [cWheelBase]         VARCHAR (50)  NULL,
    [Inactive]           BIT           NULL,
    [StartOfProdDate]    DATETIME      NULL,
    [EndOfProdDate]      DATETIME      NULL,
    [cFacelift]          VARCHAR (100) NULL,
    [WinterTyre]         BIT           NULL,
    [ModCodeInsertDate]  DATETIME      NULL,
    [Dummy]              BIT           NULL,
    [cEmissionGroup]     VARCHAR (50)  NULL,
    [Handicap]           BIT           NULL
);

