CREATE TABLE [dbo].[VIURD240_test] (
    [CompanyCode]       VARCHAR (50)  NULL,
    [AreaCode]          VARCHAR (50)  NULL,
    [Serial]            VARCHAR (50)  NULL,
    [Unit]              VARCHAR (50)  NULL,
    [Plate]             VARCHAR (50)  NULL,
    [Mileage]           VARCHAR (50)  NULL,
    [InServiceDate]     VARCHAR (50)  NULL,
    [OutServiceDate]    VARCHAR (50)  NULL,
    [MSODate]           VARCHAR (50)  NULL,
    [ModelCode]         VARCHAR (50)  NULL,
    [ModelDescription]  VARCHAR (255) NULL,
    [Column 11]         VARCHAR (50)  NULL,
    [Column 12]         VARCHAR (50)  NULL,
    [Column 13]         VARCHAR (50)  NULL,
    [Column 14]         VARCHAR (50)  NULL,
    [Column 15]         VARCHAR (50)  NULL,
    [Column 16]         VARCHAR (50)  NULL,
    [Column 17]         VARCHAR (50)  NULL,
    [Column 18]         VARCHAR (50)  NULL,
    [Column 19]         VARCHAR (50)  NULL,
    [Column 20]         VARCHAR (50)  NULL,
    [Column 21]         VARCHAR (50)  NULL,
    [SaleType]          VARCHAR (50)  NULL,
    [Column 23]         VARCHAR (50)  NULL,
    [Column 24]         VARCHAR (50)  NULL,
    [Column 25]         VARCHAR (50)  NULL,
    [Column 26]         VARCHAR (50)  NULL,
    [BuyerCode]         VARCHAR (50)  NULL,
    [BuyerName]         VARCHAR (50)  NULL,
    [BuyerAddress1]     VARCHAR (255) NULL,
    [BuyerAddress2]     VARCHAR (255) NULL,
    [BuyerAddress3]     VARCHAR (255) NULL,
    [BuyerAddress4]     VARCHAR (255) NULL,
    [BuyerFiscalCode]   VARCHAR (50)  NULL,
    [CapitalCost]       VARCHAR (50)  NULL,
    [Depreciation]      VARCHAR (50)  NULL,
    [BookValue]         VARCHAR (50)  NULL,
    [BuybackCap]        VARCHAR (50)  NULL,
    [MileCharge]        VARCHAR (50)  NULL,
    [PlusKM]            VARCHAR (50)  NULL,
    [FuelCharge]        VARCHAR (50)  NULL,
    [Damage]            VARCHAR (50)  NULL,
    [TransferFees]      VARCHAR (50)  NULL,
    [TransferFeesNoVat] VARCHAR (50)  NULL,
    [TaxDescription1]   VARCHAR (50)  NULL,
    [TaxDescription2]   VARCHAR (50)  NULL,
    [TaxDescription3]   VARCHAR (50)  NULL,
    [Column 47]         VARCHAR (50)  NULL,
    [Column 48]         VARCHAR (50)  NULL,
    [Column 49]         VARCHAR (50)  NULL,
    [Column 50]         VARCHAR (50)  NULL,
    [Column 51]         VARCHAR (50)  NULL,
    [Column 52]         VARCHAR (50)  NULL,
    [Column 53]         VARCHAR (50)  NULL,
    [Column 54]         VARCHAR (50)  NULL,
    [Column 55]         VARCHAR (50)  NULL,
    [Column 56]         VARCHAR (50)  NULL,
    [Column 57]         VARCHAR (50)  NULL,
    [Column 58]         VARCHAR (50)  NULL,
    [Column 59]         VARCHAR (50)  NULL,
    [Column 60]         VARCHAR (50)  NULL,
    [Column 61]         VARCHAR (50)  NULL
);

