//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active X Enabled:.
        /// </summary>
        internal static string ActiveXEnabled {
            get {
                return ResourceManager.GetString("ActiveXEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code :.
        /// </summary>
        internal static string AreaCode {
            get {
                return ResourceManager.GetString("AreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Name :.
        /// </summary>
        internal static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser:.
        /// </summary>
        internal static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Type:.
        /// </summary>
        internal static string BrowserType {
            get {
                return ResourceManager.GetString("BrowserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Version:.
        /// </summary>
        internal static string BrowserVersion {
            get {
                return ResourceManager.GetString("BrowserVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuyBack Cap. :.
        /// </summary>
        internal static string BuyBackCap {
            get {
                return ResourceManager.GetString("BuyBackCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer Code :.
        /// </summary>
        internal static string BuyerCode {
            get {
                return ResourceManager.GetString("BuyerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor :.
        /// </summary>
        internal static string BuyerName {
            get {
                return ResourceManager.GetString("BuyerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Cost :.
        /// </summary>
        internal static string CapitalCost {
            get {
                return ResourceManager.GetString("CapitalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company :.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country :.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days In Service :.
        /// </summary>
        internal static string DaysInService {
            get {
                return ResourceManager.GetString("DaysInService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date :.
        /// </summary>
        internal static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciation :.
        /// </summary>
        internal static string Depreciation {
            get {
                return ResourceManager.GetString("Depreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciation %:.
        /// </summary>
        internal static string DepreciationPCT {
            get {
                return ResourceManager.GetString("DepreciationPCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciation Rate:.
        /// </summary>
        internal static string DepreciationRate {
            get {
                return ResourceManager.GetString("DepreciationRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc. Type :.
        /// </summary>
        internal static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain:.
        /// </summary>
        internal static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Uploaded Date:.
        /// </summary>
        internal static string FileUploadedDate {
            get {
                return ResourceManager.GetString("FileUploadedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By:.
        /// </summary>
        internal static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Exception:.
        /// </summary>
        internal static string InnerException {
            get {
                return ResourceManager.GetString("InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Service Date :.
        /// </summary>
        internal static string InServiceDate {
            get {
                return ResourceManager.GetString("InServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From:.
        /// </summary>
        internal static string InvoiceDateFrom {
            get {
                return ResourceManager.GetString("InvoiceDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To:.
        /// </summary>
        internal static string InvoiceDateTo {
            get {
                return ResourceManager.GetString("InvoiceDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number :.
        /// </summary>
        internal static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice From:.
        /// </summary>
        internal static string InvoiceNumberFrom {
            get {
                return ResourceManager.GetString("InvoiceNumberFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice To:.
        /// </summary>
        internal static string InvoiceNumberTo {
            get {
                return ResourceManager.GetString("InvoiceNumberTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inv. Type :.
        /// </summary>
        internal static string InvoiceType {
            get {
                return ResourceManager.GetString("InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript Enabled:.
        /// </summary>
        internal static string JavaScriptEnabled {
            get {
                return ResourceManager.GetString("JavaScriptEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last activity:.
        /// </summary>
        internal static string LastActivity {
            get {
                return ResourceManager.GetString("LastActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last logged in:.
        /// </summary>
        internal static string LastLoggedIn {
            get {
                return ResourceManager.GetString("LastLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEFS - Hertz European Fleet System.
        /// </summary>
        internal static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer :.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage :.
        /// </summary>
        internal static string Mileage {
            get {
                return ResourceManager.GetString("Mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model :.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Code :.
        /// </summary>
        internal static string ModelCode {
            get {
                return ResourceManager.GetString("ModelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Group :.
        /// </summary>
        internal static string ModelGroup {
            get {
                return ResourceManager.GetString("ModelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Year :.
        /// </summary>
        internal static string ModelYear {
            get {
                return ResourceManager.GetString("ModelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSO Date :.
        /// </summary>
        internal static string MSODate {
            get {
                return ResourceManager.GetString("MSODate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Service Date :.
        /// </summary>
        internal static string OutServiceDate {
            get {
                return ResourceManager.GetString("OutServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page .
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate :.
        /// </summary>
        internal static string Plate {
            get {
                return ResourceManager.GetString("Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results per Page:.
        /// </summary>
        internal static string ResultsPerPage {
            get {
                return ResourceManager.GetString("ResultsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Date :.
        /// </summary>
        internal static string SaleDate {
            get {
                return ResourceManager.GetString("SaleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Type:.
        /// </summary>
        internal static string SaleType {
            get {
                return ResourceManager.GetString("SaleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Height:.
        /// </summary>
        internal static string ScreenHeight {
            get {
                return ResourceManager.GetString("ScreenHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Width:.
        /// </summary>
        internal static string ScreenWidth {
            get {
                return ResourceManager.GetString("ScreenWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial :.
        /// </summary>
        internal static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackTrace:.
        /// </summary>
        internal static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports Cookies:.
        /// </summary>
        internal static string SupportsCookies {
            get {
                return ResourceManager.GetString("SupportsCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports JavaScript:.
        /// </summary>
        internal static string SupportsJavaScript {
            get {
                return ResourceManager.GetString("SupportsJavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Platform:.
        /// </summary>
        internal static string SystemPlatform {
            get {
                return ResourceManager.GetString("SystemPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Site:.
        /// </summary>
        internal static string TargetSite {
            get {
                return ResourceManager.GetString("TargetSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit :.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address:.
        /// </summary>
        internal static string UserIPAddress {
            get {
                return ResourceManager.GetString("UserIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address:.
        /// </summary>
        internal static string UserIPAddress1 {
            get {
                return ResourceManager.GetString("UserIPAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged in:.
        /// </summary>
        internal static string UserLoggedIn {
            get {
                return ResourceManager.GetString("UserLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Online:.
        /// </summary>
        internal static string UsersOnline {
            get {
                return ResourceManager.GetString("UsersOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Class :.
        /// </summary>
        internal static string VehicleClass {
            get {
                return ResourceManager.GetString("VehicleClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Status :.
        /// </summary>
        internal static string VehicleStatus {
            get {
                return ResourceManager.GetString("VehicleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type :.
        /// </summary>
        internal static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows ID:.
        /// </summary>
        internal static string WindowsId {
            get {
                return ResourceManager.GetString("WindowsId", resourceCulture);
            }
        }
    }
}
