CREATE TABLE [dbo].[Application.Log] (
    [PKId]               INT           IDENTITY (1, 1) NOT NULL,
    [userId]             INT           NULL,
    [screenWidth]        INT           NULL,
    [screenHeight]       INT           NULL,
    [activeXEnabled]     BIT           NULL,
    [supportsCookies]    BIT           NULL,
    [javascriptEnabled]  BIT           NULL,
    [supportsJavascript] BIT           NULL,
    [dateLogged]         DATETIME      NULL,
    [userIPAddress]      VARCHAR (50)  NULL,
    [systemPlatform]     VARCHAR (50)  NULL,
    [browserType]        VARCHAR (50)  NULL,
    [browser]            VARCHAR (50)  NULL,
    [browserVersion]     VARCHAR (50)  NULL,
    [controlName]        VARCHAR (100) NULL,
    [referrerUrl]        VARCHAR (256) NULL,
    [requestedUrl]       VARCHAR (256) NULL,
    [method]             VARCHAR (256) NULL,
    [source]             VARCHAR (256) NULL,
    [sourceFilename]     VARCHAR (256) NULL,
    [lineNumber]         VARCHAR (50)  NULL,
    [columnNumber]       VARCHAR (50)  NULL,
    [innerException]     VARCHAR (MAX) NULL,
    [errorMessage]       VARCHAR (MAX) NULL,
    [targetSite]         VARCHAR (MAX) NULL,
    [data]               VARCHAR (MAX) NULL,
    [stacktrace]         VARCHAR (MAX) NULL,
    [resolved]           BIT           NULL,
    PRIMARY KEY CLUSTERED ([PKId] ASC)
);

