//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP.App_UserControls.Settings {
    
    
    public partial class CompaniesForm {
        
        /// <summary>
        /// UpdatePanelCompanies control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanelCompanies;
        
        /// <summary>
        /// NavigationPanelCompanies control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::APP.App_UserControls.Controls.Panel.NavigationPanel NavigationPanelCompanies;
        
        /// <summary>
        /// MultiViewCompanies control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.MultiView MultiViewCompanies;
        
        /// <summary>
        /// CompaniesList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View CompaniesList;
        
        /// <summary>
        /// ListViewCompanies control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::APP.App_UserControls.Settings.ListViews.Companies.SettingsListViewCompanies ListViewCompanies;
        
        /// <summary>
        /// CompaniesDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View CompaniesDetails;
        
        /// <summary>
        /// FormCompanies control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::APP.App_UserControls.Settings.Forms.FormCompanies.SettingsFormCompanies FormCompanies;
    }
}
