//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ListViewHeaders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListViewHeaders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ListViewHeaders", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVED.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AREA CODE.
        /// </summary>
        internal static string AreaCode {
            get {
                return ResourceManager.GetString("AreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AREA NAME.
        /// </summary>
        internal static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BANK.
        /// </summary>
        internal static string BankRegCode {
            get {
                return ResourceManager.GetString("BankRegCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELGIUM.
        /// </summary>
        internal static string Belgium {
            get {
                return ResourceManager.GetString("Belgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUYBACK.
        /// </summary>
        internal static string BuyBack {
            get {
                return ResourceManager.GetString("BuyBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUYBACK %.
        /// </summary>
        internal static string BuyBackPCT {
            get {
                return ResourceManager.GetString("BuyBackPCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODE.
        /// </summary>
        internal static string BuyerCode {
            get {
                return ResourceManager.GetString("BuyerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FISC. CODE.
        /// </summary>
        internal static string BuyerFiscalCode {
            get {
                return ResourceManager.GetString("BuyerFiscalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VENDOR.
        /// </summary>
        internal static string BuyerName {
            get {
                return ResourceManager.GetString("BuyerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX CODE.
        /// </summary>
        internal static string BuyerTaxCode {
            get {
                return ResourceManager.GetString("BuyerTaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        internal static string BuyerType {
            get {
                return ResourceManager.GetString("BuyerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMPA.
        /// </summary>
        internal static string Campa {
            get {
                return ResourceManager.GetString("Campa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORY.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2.
        /// </summary>
        internal static string CO2 {
            get {
                return ResourceManager.GetString("CO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODE.
        /// </summary>
        internal static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX CODE.
        /// </summary>
        internal static string CompanyFiscalCode {
            get {
                return ResourceManager.GetString("CompanyFiscalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        internal static string CompanyType {
            get {
                return ResourceManager.GetString("CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        internal static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        internal static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        internal static string ContactTypeName {
            get {
                return ResourceManager.GetString("ContactTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONVERSION.
        /// </summary>
        internal static string Conversion {
            get {
                return ResourceManager.GetString("Conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTRY.
        /// </summary>
        internal static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTRY.
        /// </summary>
        internal static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        internal static string CountryVat {
            get {
                return ResourceManager.GetString("CountryVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.N.
        /// </summary>
        internal static string CreditNotes {
            get {
                return ResourceManager.GetString("CreditNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENCY.
        /// </summary>
        internal static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string Day11 {
            get {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string Day12 {
            get {
                return ResourceManager.GetString("Day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string Day13 {
            get {
                return ResourceManager.GetString("Day13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string Day14 {
            get {
                return ResourceManager.GetString("Day14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string Day15 {
            get {
                return ResourceManager.GetString("Day15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string Day16 {
            get {
                return ResourceManager.GetString("Day16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        internal static string Day17 {
            get {
                return ResourceManager.GetString("Day17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string Day18 {
            get {
                return ResourceManager.GetString("Day18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        internal static string Day19 {
            get {
                return ResourceManager.GetString("Day19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string Day20 {
            get {
                return ResourceManager.GetString("Day20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string Day21 {
            get {
                return ResourceManager.GetString("Day21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string Day22 {
            get {
                return ResourceManager.GetString("Day22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        internal static string Day23 {
            get {
                return ResourceManager.GetString("Day23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string Day24 {
            get {
                return ResourceManager.GetString("Day24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string Day25 {
            get {
                return ResourceManager.GetString("Day25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        internal static string Day26 {
            get {
                return ResourceManager.GetString("Day26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        internal static string Day27 {
            get {
                return ResourceManager.GetString("Day27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string Day28 {
            get {
                return ResourceManager.GetString("Day28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.
        /// </summary>
        internal static string Day29 {
            get {
                return ResourceManager.GetString("Day29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string Day30 {
            get {
                return ResourceManager.GetString("Day30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string Day31 {
            get {
                return ResourceManager.GetString("Day31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Day6 {
            get {
                return ResourceManager.GetString("Day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Day7 {
            get {
                return ResourceManager.GetString("Day7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Day8 {
            get {
                return ResourceManager.GetString("Day8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Day9 {
            get {
                return ResourceManager.GetString("Day9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-STATUS.
        /// </summary>
        internal static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBTYPE.
        /// </summary>
        internal static string DocSubType {
            get {
                return ResourceManager.GetString("DocSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        internal static string DocType {
            get {
                return ResourceManager.GetString("DocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.SIZE.
        /// </summary>
        internal static string EngineSize {
            get {
                return ResourceManager.GetString("EngineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRORS.
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAP.
        /// </summary>
        internal static string EstimatedCap {
            get {
                return ResourceManager.GetString("EstimatedCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPR..
        /// </summary>
        internal static string EstimatedDeprRate {
            get {
                return ResourceManager.GetString("EstimatedDeprRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VB A.
        /// </summary>
        internal static string EstimatedVBAmtPeriod {
            get {
                return ResourceManager.GetString("EstimatedVBAmtPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VB.
        /// </summary>
        internal static string EstimatedVolBonus {
            get {
                return ResourceManager.GetString("EstimatedVolBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEC.
        /// </summary>
        internal static string FastSpec {
            get {
                return ResourceManager.GetString("FastSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE DATE.
        /// </summary>
        internal static string FileDate {
            get {
                return ResourceManager.GetString("FileDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE NAME.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRSTNAME.
        /// </summary>
        internal static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLEETCO.
        /// </summary>
        internal static string FleetCo {
            get {
                return ResourceManager.GetString("FleetCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRANCE.
        /// </summary>
        internal static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUEL.
        /// </summary>
        internal static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUTURE.
        /// </summary>
        internal static string Future {
            get {
                return ResourceManager.GetString("Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GERMANY.
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP.
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INACTIVE.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.S.DATE.
        /// </summary>
        internal static string InServiceDate {
            get {
                return ResourceManager.GetString("InServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        internal static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVOICE.
        /// </summary>
        internal static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE.
        /// </summary>
        internal static string InvoicesBE {
            get {
                return ResourceManager.GetString("InvoicesBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FR.
        /// </summary>
        internal static string InvoicesFR {
            get {
                return ResourceManager.GetString("InvoicesFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GE.
        /// </summary>
        internal static string InvoicesGE {
            get {
                return ResourceManager.GetString("InvoicesGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        internal static string InvoicesIT {
            get {
                return ResourceManager.GetString("InvoicesIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LU.
        /// </summary>
        internal static string InvoicesLU {
            get {
                return ResourceManager.GetString("InvoicesLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        internal static string InvoicesNE {
            get {
                return ResourceManager.GetString("InvoicesNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP.
        /// </summary>
        internal static string InvoicesSP {
            get {
                return ResourceManager.GetString("InvoicesSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SZ.
        /// </summary>
        internal static string InvoicesSZ {
            get {
                return ResourceManager.GetString("InvoicesSZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        internal static string InvoiceStatus {
            get {
                return ResourceManager.GetString("InvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK.
        /// </summary>
        internal static string InvoicesUK {
            get {
                return ResourceManager.GetString("InvoicesUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        internal static string InvoiceTotal {
            get {
                return ResourceManager.GetString("InvoiceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        internal static string InvoiceType {
            get {
                return ResourceManager.GetString("InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALID.
        /// </summary>
        internal static string IsCorrect {
            get {
                return ResourceManager.GetString("IsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETED.
        /// </summary>
        internal static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUPLICATE.
        /// </summary>
        internal static string IsDuplicate {
            get {
                return ResourceManager.GetString("IsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAR.
        /// </summary>
        internal static string IsExported {
            get {
                return ResourceManager.GetString("IsExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALID.
        /// </summary>
        internal static string IsValid {
            get {
                return ResourceManager.GetString("IsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITALY.
        /// </summary>
        internal static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITV.
        /// </summary>
        internal static string ITVSerial {
            get {
                return ResourceManager.GetString("ITVSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST ACTIVITY.
        /// </summary>
        internal static string LastActivity {
            get {
                return ResourceManager.GetString("LastActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST LOGIN.
        /// </summary>
        internal static string LastLoggedIn {
            get {
                return ResourceManager.GetString("LastLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST SALE.
        /// </summary>
        internal static string LastSaleDate {
            get {
                return ResourceManager.GetString("LastSaleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEASE.
        /// </summary>
        internal static string Lease {
            get {
                return ResourceManager.GetString("Lease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEASE %.
        /// </summary>
        internal static string LeasePCT {
            get {
                return ResourceManager.GetString("LeasePCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESTINY.
        /// </summary>
        internal static string LocationCity {
            get {
                return ResourceManager.GetString("LocationCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCKED OUT.
        /// </summary>
        internal static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUXEMBOURG.
        /// </summary>
        internal static string Luxembourg {
            get {
                return ResourceManager.GetString("Luxembourg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANUFACTURER.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANUFACTURER.
        /// </summary>
        internal static string ManufacturerName {
            get {
                return ResourceManager.GetString("ManufacturerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MILEAGE.
        /// </summary>
        internal static string Mileage {
            get {
                return ResourceManager.GetString("Mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODEL.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODEL.
        /// </summary>
        internal static string ModelCode {
            get {
                return ResourceManager.GetString("ModelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESC..
        /// </summary>
        internal static string ModelDescription {
            get {
                return ResourceManager.GetString("ModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP.
        /// </summary>
        internal static string ModelGroup {
            get {
                return ResourceManager.GetString("ModelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL MODELS.
        /// </summary>
        internal static string ModelsCount {
            get {
                return ResourceManager.GetString("ModelsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEAR.
        /// </summary>
        internal static string ModelYear {
            get {
                return ResourceManager.GetString("ModelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JANUARY.
        /// </summary>
        internal static string Month1 {
            get {
                return ResourceManager.GetString("Month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCTOBER.
        /// </summary>
        internal static string Month10 {
            get {
                return ResourceManager.GetString("Month10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOVEMBER.
        /// </summary>
        internal static string Month11 {
            get {
                return ResourceManager.GetString("Month11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECEMBER.
        /// </summary>
        internal static string Month12 {
            get {
                return ResourceManager.GetString("Month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEBRUARY.
        /// </summary>
        internal static string Month2 {
            get {
                return ResourceManager.GetString("Month2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARCH.
        /// </summary>
        internal static string Month3 {
            get {
                return ResourceManager.GetString("Month3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APRIL.
        /// </summary>
        internal static string Month4 {
            get {
                return ResourceManager.GetString("Month4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAY.
        /// </summary>
        internal static string Month5 {
            get {
                return ResourceManager.GetString("Month5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUNE.
        /// </summary>
        internal static string Month6 {
            get {
                return ResourceManager.GetString("Month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JULY.
        /// </summary>
        internal static string Month7 {
            get {
                return ResourceManager.GetString("Month7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUGUST.
        /// </summary>
        internal static string Month8 {
            get {
                return ResourceManager.GetString("Month8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPTEMBER.
        /// </summary>
        internal static string Month9 {
            get {
                return ResourceManager.GetString("Month9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSO.
        /// </summary>
        internal static string MSODate {
            get {
                return ResourceManager.GetString("MSODate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETHERLANDS.
        /// </summary>
        internal static string Netherlands {
            get {
                return ResourceManager.GetString("Netherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTES.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO PAY. DUE.
        /// </summary>
        internal static string No_Payment_Due {
            get {
                return ResourceManager.GetString("No_Payment_Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRC.
        /// </summary>
        internal static string NrcDate {
            get {
                return ResourceManager.GetString("NrcDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPCO.
        /// </summary>
        internal static string OpCo {
            get {
                return ResourceManager.GetString("OpCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORACLE.
        /// </summary>
        internal static string OracleCode {
            get {
                return ResourceManager.GetString("OracleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORIGINAL.
        /// </summary>
        internal static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHER.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLATE.
        /// </summary>
        internal static string Plate {
            get {
                return ResourceManager.GetString("Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSED.
        /// </summary>
        internal static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RACFID.
        /// </summary>
        internal static string Racfid {
            get {
                return ResourceManager.GetString("Racfid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RATE.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RATE.
        /// </summary>
        internal static string RateClass {
            get {
                return ResourceManager.GetString("RateClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        internal static string ReceivableStoreDate {
            get {
                return ResourceManager.GetString("ReceivableStoreDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGION.
        /// </summary>
        internal static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX AMT..
        /// </summary>
        internal static string RegTaxAmount {
            get {
                return ResourceManager.GetString("RegTaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.D.N..
        /// </summary>
        internal static string SaleDocumentNumber {
            get {
                return ResourceManager.GetString("SaleDocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERIAL.
        /// </summary>
        internal static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPAIN.
        /// </summary>
        internal static string Spain {
            get {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SURNAME.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUSPEND.
        /// </summary>
        internal static string Suspend {
            get {
                return ResourceManager.GetString("Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWITZERLAND.
        /// </summary>
        internal static string Switzerland {
            get {
                return ResourceManager.GetString("Switzerland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAS.
        /// </summary>
        internal static string TasModelCode {
            get {
                return ResourceManager.GetString("TasModelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX CODE.
        /// </summary>
        internal static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX.
        /// </summary>
        internal static string TaxDate {
            get {
                return ResourceManager.GetString("TaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX PCT.
        /// </summary>
        internal static string TaxPCT {
            get {
                return ResourceManager.GetString("TaxPCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        internal static string TotalInvoices {
            get {
                return ResourceManager.GetString("TotalInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string TotalPCT {
            get {
                return ResourceManager.GetString("TotalPCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL SALES.
        /// </summary>
        internal static string TotalSales {
            get {
                return ResourceManager.GetString("TotalSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK.
        /// </summary>
        internal static string Uk {
            get {
                return ResourceManager.GetString("Uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIT.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODE.
        /// </summary>
        internal static string VehicleCode {
            get {
                return ResourceManager.GetString("VehicleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        internal static string VehicleStatus {
            get {
                return ResourceManager.GetString("VehicleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        internal static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RISK.
        /// </summary>
        internal static string WholeSale {
            get {
                return ResourceManager.GetString("WholeSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RISK %.
        /// </summary>
        internal static string WholeSalePCT {
            get {
                return ResourceManager.GetString("WholeSalePCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRECK.
        /// </summary>
        internal static string Wreck {
            get {
                return ResourceManager.GetString("Wreck", resourceCulture);
            }
        }
    }
}
