//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ListItems {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListItems() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ListItems", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuyerName.
        /// </summary>
        internal static string BuyerName {
            get {
                return ResourceManager.GetString("BuyerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyCode.
        /// </summary>
        internal static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyFiscalCode.
        /// </summary>
        internal static string CompanyFiscalCode {
            get {
                return ResourceManager.GetString("CompanyFiscalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyName.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyType.
        /// </summary>
        internal static string CompanyType {
            get {
                return ResourceManager.GetString("CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryName.
        /// </summary>
        internal static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryVat.
        /// </summary>
        internal static string CountryVat {
            get {
                return ResourceManager.GetString("CountryVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyCode.
        /// </summary>
        internal static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive.
        /// </summary>
        internal static string Exclusive {
            get {
                return ResourceManager.GetString("Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        internal static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InServiceDate.
        /// </summary>
        internal static string InServiceDate {
            get {
                return ResourceManager.GetString("InServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 Days.
        /// </summary>
        internal static string Last30Days {
            get {
                return ResourceManager.GetString("Last30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 Days.
        /// </summary>
        internal static string Last7Days {
            get {
                return ResourceManager.GetString("Last7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Activity.
        /// </summary>
        internal static string LastActivity {
            get {
                return ResourceManager.GetString("LastActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login.
        /// </summary>
        internal static string LastLoggedIn {
            get {
                return ResourceManager.GetString("LastLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        internal static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        internal static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Out.
        /// </summary>
        internal static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage.
        /// </summary>
        internal static string Mileage {
            get {
                return ResourceManager.GetString("Mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Month.
        /// </summary>
        internal static string NextMonth {
            get {
                return ResourceManager.GetString("NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Year.
        /// </summary>
        internal static string NextYear {
            get {
                return ResourceManager.GetString("NextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - None Selected -.
        /// </summary>
        internal static string NoneSelected {
            get {
                return ResourceManager.GetString("NoneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Optional -.
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate.
        /// </summary>
        internal static string Plate {
            get {
                return ResourceManager.GetString("Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Please Select -.
        /// </summary>
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RACFID.
        /// </summary>
        internal static string RacfId {
            get {
                return ResourceManager.GetString("RacfId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegionName.
        /// </summary>
        internal static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select All -.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        internal static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Show All -.
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        internal static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month-to-Date.
        /// </summary>
        internal static string ThisMonthToDate {
            get {
                return ResourceManager.GetString("ThisMonthToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month-to-Date.
        /// </summary>
        internal static string ThisMonthToDate1 {
            get {
                return ResourceManager.GetString("ThisMonthToDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        internal static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        internal static string ThisYear1 {
            get {
                return ResourceManager.GetString("ThisYear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year-to-Date.
        /// </summary>
        internal static string ThisYearToDate {
            get {
                return ResourceManager.GetString("ThisYearToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year-to-Date.
        /// </summary>
        internal static string ThisYearToDate1 {
            get {
                return ResourceManager.GetString("ThisYearToDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today-to-Year End.
        /// </summary>
        internal static string TodayToYearEnd {
            get {
                return ResourceManager.GetString("TodayToYearEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VehicleType.
        /// </summary>
        internal static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year End + 2.
        /// </summary>
        internal static string YearEndPlusTwo {
            get {
                return ResourceManager.GetString("YearEndPlusTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
