//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ToolTips", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active - Click to sort asc / desc..
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount - Click to sort asc / desc..
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved - Click to sort asc / desc..
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code - Click to sort asc / desc..
        /// </summary>
        internal static string AreaCode {
            get {
                return ResourceManager.GetString("AreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Name - Click to sort asc / desc..
        /// </summary>
        internal static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Code - Click to sort asc / desc..
        /// </summary>
        internal static string BankRegCode {
            get {
                return ResourceManager.GetString("BankRegCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium - Click to sort asc / desc..
        /// </summary>
        internal static string Belgium {
            get {
                return ResourceManager.GetString("Belgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuyBack - Click to sort asc / desc..
        /// </summary>
        internal static string BuyBack {
            get {
                return ResourceManager.GetString("BuyBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuyBack %  - Click to sort asc / desc..
        /// </summary>
        internal static string BuyBackPCT {
            get {
                return ResourceManager.GetString("BuyBackPCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer Code  - Click to sort asc / desc..
        /// </summary>
        internal static string BuyerCode {
            get {
                return ResourceManager.GetString("BuyerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Code - Click to sort asc / desc..
        /// </summary>
        internal static string BuyerFiscalCode {
            get {
                return ResourceManager.GetString("BuyerFiscalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor  - Click to sort asc / desc..
        /// </summary>
        internal static string BuyerName {
            get {
                return ResourceManager.GetString("BuyerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code - Click to sort asc / desc..
        /// </summary>
        internal static string BuyerTaxCode {
            get {
                return ResourceManager.GetString("BuyerTaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuyerType - Click to sort asc / desc..
        /// </summary>
        internal static string BuyerType {
            get {
                return ResourceManager.GetString("BuyerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campa  - Click to sort asc / desc..
        /// </summary>
        internal static string Campa {
            get {
                return ResourceManager.GetString("Campa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category  - Click to sort asc / desc..
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2  - Click to sort asc / desc..
        /// </summary>
        internal static string CO2 {
            get {
                return ResourceManager.GetString("CO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code - Click to sort asc / desc..
        /// </summary>
        internal static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code - Click to sort asc / desc..
        /// </summary>
        internal static string CompanyFiscalCode {
            get {
                return ResourceManager.GetString("CompanyFiscalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name - Click to sort asc / desc..
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type - Click to sort asc / desc..
        /// </summary>
        internal static string CompanyType {
            get {
                return ResourceManager.GetString("CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email  - Click to sort asc / desc..
        /// </summary>
        internal static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact - Click to sort asc / desc..
        /// </summary>
        internal static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type - Click to sort asc / desc..
        /// </summary>
        internal static string ContactTypeName {
            get {
                return ResourceManager.GetString("ContactTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion - Click to sort asc / desc..
        /// </summary>
        internal static string Conversion {
            get {
                return ResourceManager.GetString("Conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code  - Click to sort asc / desc..
        /// </summary>
        internal static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country - Click to sort asc / desc..
        /// </summary>
        internal static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat - Click to sort asc / desc..
        /// </summary>
        internal static string CountryVat {
            get {
                return ResourceManager.GetString("CountryVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Notes - Click to sort asc / desc..
        /// </summary>
        internal static string CreditNotes {
            get {
                return ResourceManager.GetString("CreditNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency - Click to sort asc / desc..
        /// </summary>
        internal static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current - Click to sort asc / desc..
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a date..
        /// </summary>
        internal static string DatePicker {
            get {
                return ResourceManager.GetString("DatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select or enter a valid date. (Format dd/MM/yyyy).
        /// </summary>
        internal static string DateSelect {
            get {
                return ResourceManager.GetString("DateSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Click to sort asc / desc..
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 - Click to sort asc / desc..
        /// </summary>
        internal static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11 - Click to sort asc / desc..
        /// </summary>
        internal static string Day11 {
            get {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 - Click to sort asc / desc..
        /// </summary>
        internal static string Day12 {
            get {
                return ResourceManager.GetString("Day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13 - Click to sort asc / desc..
        /// </summary>
        internal static string Day13 {
            get {
                return ResourceManager.GetString("Day13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 - Click to sort asc / desc..
        /// </summary>
        internal static string Day14 {
            get {
                return ResourceManager.GetString("Day14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 - Click to sort asc / desc..
        /// </summary>
        internal static string Day15 {
            get {
                return ResourceManager.GetString("Day15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 - Click to sort asc / desc..
        /// </summary>
        internal static string Day16 {
            get {
                return ResourceManager.GetString("Day16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17 - Click to sort asc / desc..
        /// </summary>
        internal static string Day17 {
            get {
                return ResourceManager.GetString("Day17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18 - Click to sort asc / desc..
        /// </summary>
        internal static string Day18 {
            get {
                return ResourceManager.GetString("Day18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19 - Click to sort asc / desc..
        /// </summary>
        internal static string Day19 {
            get {
                return ResourceManager.GetString("Day19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Click to sort asc / desc..
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 - Click to sort asc / desc..
        /// </summary>
        internal static string Day20 {
            get {
                return ResourceManager.GetString("Day20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21 - Click to sort asc / desc..
        /// </summary>
        internal static string Day21 {
            get {
                return ResourceManager.GetString("Day21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22 - Click to sort asc / desc..
        /// </summary>
        internal static string Day22 {
            get {
                return ResourceManager.GetString("Day22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23 - Click to sort asc / desc..
        /// </summary>
        internal static string Day23 {
            get {
                return ResourceManager.GetString("Day23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 - Click to sort asc / desc..
        /// </summary>
        internal static string Day24 {
            get {
                return ResourceManager.GetString("Day24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 - Click to sort asc / desc..
        /// </summary>
        internal static string Day25 {
            get {
                return ResourceManager.GetString("Day25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26 - Click to sort asc / desc..
        /// </summary>
        internal static string Day26 {
            get {
                return ResourceManager.GetString("Day26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27 - Click to sort asc / desc..
        /// </summary>
        internal static string Day27 {
            get {
                return ResourceManager.GetString("Day27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28 - Click to sort asc / desc..
        /// </summary>
        internal static string Day28 {
            get {
                return ResourceManager.GetString("Day28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29 - Click to sort asc / desc..
        /// </summary>
        internal static string Day29 {
            get {
                return ResourceManager.GetString("Day29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Click to sort asc / desc..
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 - Click to sort asc / desc..
        /// </summary>
        internal static string Day30 {
            get {
                return ResourceManager.GetString("Day30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31 - Click to sort asc / desc..
        /// </summary>
        internal static string Day31 {
            get {
                return ResourceManager.GetString("Day31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Click to sort asc / desc..
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 - Click to sort asc / desc..
        /// </summary>
        internal static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - Click to sort asc / desc..
        /// </summary>
        internal static string Day6 {
            get {
                return ResourceManager.GetString("Day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 - Click to sort asc / desc..
        /// </summary>
        internal static string Day7 {
            get {
                return ResourceManager.GetString("Day7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 - Click to sort asc / desc..
        /// </summary>
        internal static string Day8 {
            get {
                return ResourceManager.GetString("Day8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 - Click to sort asc / desc..
        /// </summary>
        internal static string Day9 {
            get {
                return ResourceManager.GetString("Day9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Status - Click to sort asc / desc..
        /// </summary>
        internal static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Sub Type  - Click to sort asc / desc..
        /// </summary>
        internal static string DocSubType {
            get {
                return ResourceManager.GetString("DocSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type  - Click to sort asc / desc..
        /// </summary>
        internal static string DocType {
            get {
                return ResourceManager.GetString("DocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users email address - Click to sort asc / desc..
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Sixe - Click to sort asc / desc..
        /// </summary>
        internal static string EngineSize {
            get {
                return ResourceManager.GetString("EngineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid password..
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Windows user ID..
        /// </summary>
        internal static string EnterWindowsId {
            get {
                return ResourceManager.GetString("EnterWindowsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors - Click to sort asc / desc..
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Cap. - Click to sort asc / desc..
        /// </summary>
        internal static string EstimatedCap {
            get {
                return ResourceManager.GetString("EstimatedCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Depr. Rate - Click to sort asc / desc..
        /// </summary>
        internal static string EstimatedDeprRate {
            get {
                return ResourceManager.GetString("EstimatedDeprRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Vol. Bonus Amt. Period - Click to sort asc / desc..
        /// </summary>
        internal static string EstimatedVBAmtPeriod {
            get {
                return ResourceManager.GetString("EstimatedVBAmtPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Vol. Bonus - Click to sort asc / desc..
        /// </summary>
        internal static string EstimatedVolBonus {
            get {
                return ResourceManager.GetString("EstimatedVolBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Spec - Click to sort asc / desc..
        /// </summary>
        internal static string FastSpec {
            get {
                return ResourceManager.GetString("FastSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Date - - Click to sort asc / desc..
        /// </summary>
        internal static string FileDate {
            get {
                return ResourceManager.GetString("FileDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name - Click to sort asc / desc..
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname - Click to sort asc / desc..
        /// </summary>
        internal static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FleetCo - Click to sort asc / desc..
        /// </summary>
        internal static string FleetCo {
            get {
                return ResourceManager.GetString("FleetCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France - Click to sort asc / desc..
        /// </summary>
        internal static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Type - Click to sort asc / desc..
        /// </summary>
        internal static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiture ISD - Click to sort asc / desc..
        /// </summary>
        internal static string Future {
            get {
                return ResourceManager.GetString("Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany - Click to sort asc / desc..
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name  - Click to sort asc / desc..
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to go application home page..
        /// </summary>
        internal static string HertzLogo {
            get {
                return ResourceManager.GetString("HertzLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to go to help home page..
        /// </summary>
        internal static string HertzLogoHelp {
            get {
                return ResourceManager.GetString("HertzLogoHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive - Click to sort asc / desc..
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Service Date  - Click to sort asc / desc..
        /// </summary>
        internal static string InServiceDate {
            get {
                return ResourceManager.GetString("InServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date  - Click to sort asc / desc..
        /// </summary>
        internal static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number  - Click to sort asc / desc..
        /// </summary>
        internal static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE - Click to sort asc / desc..
        /// </summary>
        internal static string InvoicesBE {
            get {
                return ResourceManager.GetString("InvoicesBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FR - Click to sort asc / desc..
        /// </summary>
        internal static string InvoicesFR {
            get {
                return ResourceManager.GetString("InvoicesFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GE - Click to sort asc / desc..
        /// </summary>
        internal static string InvoicesGE {
            get {
                return ResourceManager.GetString("InvoicesGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT - Click to sort asc / desc..
        /// </summary>
        internal static string InvoicesIT {
            get {
                return ResourceManager.GetString("InvoicesIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LU - Click to sort asc / desc..
        /// </summary>
        internal static string InvoicesLU {
            get {
                return ResourceManager.GetString("InvoicesLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE - Click to sort asc / desc..
        /// </summary>
        internal static string InvoicesNE {
            get {
                return ResourceManager.GetString("InvoicesNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP - Click to sort asc / desc..
        /// </summary>
        internal static string InvoicesSP {
            get {
                return ResourceManager.GetString("InvoicesSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SZ - Click to sort asc / desc..
        /// </summary>
        internal static string InvoicesSZ {
            get {
                return ResourceManager.GetString("InvoicesSZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status - Click to sort asc / desc..
        /// </summary>
        internal static string InvoiceStatus {
            get {
                return ResourceManager.GetString("InvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK - Click to sort asc / desc..
        /// </summary>
        internal static string InvoicesUK {
            get {
                return ResourceManager.GetString("InvoicesUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total - Click to sort asc / desc..
        /// </summary>
        internal static string InvoiceTotal {
            get {
                return ResourceManager.GetString("InvoiceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Type - Click to sort asc / desc..
        /// </summary>
        internal static string InvoiceType {
            get {
                return ResourceManager.GetString("InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Correct - Click to sort asc / desc..
        /// </summary>
        internal static string IsCorrect {
            get {
                return ResourceManager.GetString("IsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is deleted - Click to sort asc / desc..
        /// </summary>
        internal static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate - Click to sort asc / desc..
        /// </summary>
        internal static string IsDuplicate {
            get {
                return ResourceManager.GetString("IsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars - Click to sort asc / desc..
        /// </summary>
        internal static string IsExported {
            get {
                return ResourceManager.GetString("IsExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Valid - Click to sort asc / desc..
        /// </summary>
        internal static string IsValid {
            get {
                return ResourceManager.GetString("IsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy - Click to sort asc / desc..
        /// </summary>
        internal static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITV  - Click to sort asc / desc..
        /// </summary>
        internal static string ITVSerial {
            get {
                return ResourceManager.GetString("ITVSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users last activity - Click to sort asc / desc..
        /// </summary>
        internal static string LastActivity {
            get {
                return ResourceManager.GetString("LastActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User last logged in - Click to sort asc / desc..
        /// </summary>
        internal static string LastLoggedIn {
            get {
                return ResourceManager.GetString("LastLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Sale Date - Click to sort asc / desc..
        /// </summary>
        internal static string LastSaleDate {
            get {
                return ResourceManager.GetString("LastSaleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease - Click to sort asc / desc..
        /// </summary>
        internal static string Lease {
            get {
                return ResourceManager.GetString("Lease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease %  - Click to sort asc / desc..
        /// </summary>
        internal static string LeasePCT {
            get {
                return ResourceManager.GetString("LeasePCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to edit / view details of selected item..
        /// </summary>
        internal static string ListViewDetails {
            get {
                return ResourceManager.GetString("ListViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destiny  - Click to sort asc / desc..
        /// </summary>
        internal static string LocationCity {
            get {
                return ResourceManager.GetString("LocationCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is locked out - Click to sort asc / desc..
        /// </summary>
        internal static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to return to the Login page..
        /// </summary>
        internal static string LoginBack {
            get {
                return ResourceManager.GetString("LoginBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg - Click to sort asc / desc..
        /// </summary>
        internal static string Luxembourg {
            get {
                return ResourceManager.GetString("Luxembourg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer  - Click to sort asc / desc..
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer - Click to sort asc / desc..
        /// </summary>
        internal static string ManufacturerName {
            get {
                return ResourceManager.GetString("ManufacturerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage  - Click to sort asc / desc..
        /// </summary>
        internal static string Mileage {
            get {
                return ResourceManager.GetString("Mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model  - Click to sort asc / desc..
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Code  - Click to sort asc / desc..
        /// </summary>
        internal static string ModelCode {
            get {
                return ResourceManager.GetString("ModelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Description - Click to sort asc / desc..
        /// </summary>
        internal static string ModelDescription {
            get {
                return ResourceManager.GetString("ModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Group - Click to sort asc / desc..
        /// </summary>
        internal static string ModelGroup {
            get {
                return ResourceManager.GetString("ModelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Models - Click to sort asc / desc..
        /// </summary>
        internal static string ModelsCount {
            get {
                return ResourceManager.GetString("ModelsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Year - Click to sort asc / desc..
        /// </summary>
        internal static string ModelYear {
            get {
                return ResourceManager.GetString("ModelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JANUARY - Click to sort asc / desc..
        /// </summary>
        internal static string Month1 {
            get {
                return ResourceManager.GetString("Month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCTOBER - Click to sort asc / desc..
        /// </summary>
        internal static string Month10 {
            get {
                return ResourceManager.GetString("Month10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOVEMBER - Click to sort asc / desc..
        /// </summary>
        internal static string Month11 {
            get {
                return ResourceManager.GetString("Month11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECEMBER - Click to sort asc / desc..
        /// </summary>
        internal static string Month12 {
            get {
                return ResourceManager.GetString("Month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEBRUARY - Click to sort asc / desc..
        /// </summary>
        internal static string Month2 {
            get {
                return ResourceManager.GetString("Month2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARCH - Click to sort asc / desc..
        /// </summary>
        internal static string Month3 {
            get {
                return ResourceManager.GetString("Month3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APRIL - Click to sort asc / desc..
        /// </summary>
        internal static string Month4 {
            get {
                return ResourceManager.GetString("Month4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAY - Click to sort asc / desc..
        /// </summary>
        internal static string Month5 {
            get {
                return ResourceManager.GetString("Month5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUNE - Click to sort asc / desc..
        /// </summary>
        internal static string Month6 {
            get {
                return ResourceManager.GetString("Month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JULY - Click to sort asc / desc..
        /// </summary>
        internal static string Month7 {
            get {
                return ResourceManager.GetString("Month7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUGUST - Click to sort asc / desc..
        /// </summary>
        internal static string Month8 {
            get {
                return ResourceManager.GetString("Month8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPTEMBER - Click to sort asc / desc..
        /// </summary>
        internal static string Month9 {
            get {
                return ResourceManager.GetString("Month9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to first page..
        /// </summary>
        internal static string MoveFirst {
            get {
                return ResourceManager.GetString("MoveFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to last page..
        /// </summary>
        internal static string MoveLast {
            get {
                return ResourceManager.GetString("MoveLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to next page..
        /// </summary>
        internal static string MoveNext {
            get {
                return ResourceManager.GetString("MoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to previous page..
        /// </summary>
        internal static string MovePrevious {
            get {
                return ResourceManager.GetString("MovePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSO Date - Click to sort asc / desc..
        /// </summary>
        internal static string MSODate {
            get {
                return ResourceManager.GetString("MSODate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands - Click to sort asc / desc..
        /// </summary>
        internal static string Netherlands {
            get {
                return ResourceManager.GetString("Netherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes - Click to sort asc / desc..
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Payment Due - Click to sort asc / desc..
        /// </summary>
        internal static string No_Payment_Due {
            get {
                return ResourceManager.GetString("No_Payment_Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nrc - Click to sort asc / desc..
        /// </summary>
        internal static string NrcDate {
            get {
                return ResourceManager.GetString("NrcDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpCo - Click to sort asc / desc..
        /// </summary>
        internal static string OpCo {
            get {
                return ResourceManager.GetString("OpCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle Code - Click to sort asc / desc..
        /// </summary>
        internal static string OracleCode {
            get {
                return ResourceManager.GetString("OracleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original - Click to sort asc / desc..
        /// </summary>
        internal static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other - Click to sort asc / desc..
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select serials and amounts and click here..
        /// </summary>
        internal static string PasteSerial {
            get {
                return ResourceManager.GetString("PasteSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate  - Click to sort asc / desc..
        /// </summary>
        internal static string Plate {
            get {
                return ResourceManager.GetString("Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed - Click to sort asc / desc..
        /// </summary>
        internal static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RACFID - Click to sort asc / desc..
        /// </summary>
        internal static string Racfid {
            get {
                return ResourceManager.GetString("Racfid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate - Click to sort asc / desc..
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Class - Click to sort asc / desc..
        /// </summary>
        internal static string RateClass {
            get {
                return ResourceManager.GetString("RateClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receivable Stored Date - Click to sort asc / desc..
        /// </summary>
        internal static string ReceivableStoreDate {
            get {
                return ResourceManager.GetString("ReceivableStoreDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to refresh current selection..
        /// </summary>
        internal static string RefreshListView {
            get {
                return ResourceManager.GetString("RefreshListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region - Click to sort asc / desc..
        /// </summary>
        internal static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg Tax Amount - Click to sort asc / desc..
        /// </summary>
        internal static string RegTaxAmount {
            get {
                return ResourceManager.GetString("RegTaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Document Number - Click to sort asc / desc..
        /// </summary>
        internal static string SaleDocumentNumber {
            get {
                return ResourceManager.GetString("SaleDocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select domain to login..
        /// </summary>
        internal static string SelectDomain {
            get {
                return ResourceManager.GetString("SelectDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial  - Click to sort asc / desc..
        /// </summary>
        internal static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain - Click to sort asc / desc..
        /// </summary>
        internal static string Spain {
            get {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname - Click to sort asc / desc..
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend - Click to sort asc / desc..
        /// </summary>
        internal static string Suspend {
            get {
                return ResourceManager.GetString("Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland - Click to sort asc / desc..
        /// </summary>
        internal static string Switzerland {
            get {
                return ResourceManager.GetString("Switzerland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to view system information and requirements..
        /// </summary>
        internal static string SystemInformation {
            get {
                return ResourceManager.GetString("SystemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAS Model Code - Click to sort asc / desc..
        /// </summary>
        internal static string TasModelCode {
            get {
                return ResourceManager.GetString("TasModelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code  - Click to sort asc / desc..
        /// </summary>
        internal static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Date - Click to sort asc / desc..
        /// </summary>
        internal static string TaxDate {
            get {
                return ResourceManager.GetString("TaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Pct  - Click to sort asc / desc..
        /// </summary>
        internal static string TaxPCT {
            get {
                return ResourceManager.GetString("TaxPCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter a Buyer Code.
        /// </summary>
        internal static string TextBuyerCode {
            get {
                return ResourceManager.GetString("TextBuyerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Buyer Code cannot be empty..
        /// </summary>
        internal static string TextBuyerCodeError {
            get {
                return ResourceManager.GetString("TextBuyerCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total - Click to sort asc / desc..
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Invoices -  Click to sort asc / desc..
        /// </summary>
        internal static string TotalInvoices {
            get {
                return ResourceManager.GetString("TotalInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total % - Click to sort asc / desc..
        /// </summary>
        internal static string TotalPCT {
            get {
                return ResourceManager.GetString("TotalPCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales  - Click to sort asc / desc..
        /// </summary>
        internal static string TotalSales {
            get {
                return ResourceManager.GetString("TotalSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK - Click to sort asc / desc..
        /// </summary>
        internal static string Uk {
            get {
                return ResourceManager.GetString("Uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit  - Click to sort asc / desc..
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Code - Click to sort asc / desc..
        /// </summary>
        internal static string VehicleCode {
            get {
                return ResourceManager.GetString("VehicleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Status - Click to sort asc / desc..
        /// </summary>
        internal static string VehicleStatus {
            get {
                return ResourceManager.GetString("VehicleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type  - Click to sort asc / desc..
        /// </summary>
        internal static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WholeSale  - Click to sort asc / desc..
        /// </summary>
        internal static string WholeSale {
            get {
                return ResourceManager.GetString("WholeSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WholeSale %  - Click to sort asc / desc..
        /// </summary>
        internal static string WholeSalePCT {
            get {
                return ResourceManager.GetString("WholeSalePCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wreck - Click to sort asc / desc..
        /// </summary>
        internal static string Wreck {
            get {
                return ResourceManager.GetString("Wreck", resourceCulture);
            }
        }
    }
}
