-- =============================================
-- Author:		Javier
-- Create date: October 2011
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[spDBImportActiveFleetMonthUpload]
		@CompanyCode				VARCHAR(20) = NULL,
		@Serial						VARCHAR(50) = NULL,
		@AreaCode					VARCHAR(20) = NULL,
		@Unit						VARCHAR(20) = NULL,
		@UnitLastDigit				VARCHAR(10) = NULL,
		@Plate						VARCHAR(20) = NULL,
		@InvoiceStatus				VARCHAR(10) = NULL,
		@SalePrice					VARCHAR(20) = NULL,
		@CapitalCost				VARCHAR(20) = NULL,
		@Depreciation				VARCHAR(20) = NULL,
		@DepreciationRate			VARCHAR(20) = NULL,
		@DepreciationPCT			VARCHAR(20) = NULL,
		@BuyBackCap					VARCHAR(20) = NULL,
		@LessOr						VARCHAR(50) = NULL,
		@BaseAndOptions				VARCHAR(50) = NULL,
		@SaleType					VARCHAR(10) = NULL,
		@VehicleClass				VARCHAR(20) = NULL,
		@VehicleStatus				VARCHAR(20) = NULL,
		@SpecialProgramIndicator	VARCHAR(20) = NULL,
		@ManufacturerCode			VARCHAR(20) = NULL,
		@ModelYear					VARCHAR(20) = NULL,
		@ModelCode					VARCHAR(30) = NULL,
		@PaymentMethod				VARCHAR(30) = NULL,
		@InvoiceNumber				VARCHAR(50) = NULL,
		@DeliveryDate				VARCHAR(20) = NULL,
		@InServiceDate				VARCHAR(20) = NULL,
		@OutServiceDate				VARCHAR(20) = NULL,
		@SaleDate					VARCHAR(20) = NULL,
		@MSODate					VARCHAR(20) = NULL,
		@VehicleType				VARCHAR(20) = NULL,
		@PL							VARCHAR(20) = NULL,
		@Mileage					VARCHAR(20) = NULL,
		@DaysInService				VARCHAR(20) = NULL,
		@BuyerCode					VARCHAR(50) = NULL,
		@PDepreciationRate			VARCHAR(20) = NULL,
		@PDepreciationPCT			VARCHAR(20) = NULL,
		@TasModel					VARCHAR(20) = NULL,
		@SubType					VARCHAR(20) = NULL,
		@SaleDocumentNumber			VARCHAR(50) = NULL,
		@ProgramCAP					VARCHAR(50) = NULL,
		@ProgramAccumDepreciation	VARCHAR(50) = NULL,
		@Reference					VARCHAR(50) = NULL
	
AS
BEGIN
	
	SET NOCOUNT ON;
	
	INSERT INTO [Import.ActiveFleetMonth]
	(
		CompanyCode,
		Serial,
		AreaCode,
		Unit,
		UnitLastDigit,
		Plate,
		InvoiceStatus,
		SalePrice,
		CapitalCost,
		Depreciation,
		DepreciationRate,
		DepreciationPCT,
		BuyBackCap,
		LessOr,
		BaseAndOptions,
		SaleType,
		VehicleClass,
		VehicleStatus,
		SpecialProgramIndicator,
		ManufacturerCode,
		ModelYear,
		ModelCode,
		PaymentMethod,
		InvoiceNumber,
		DeliveryDate,
		InServiceDate,
		OutServiceDate,
		SaleDate,
		MSODate,
		VehicleType,
		PL,
		Mileage,
		DaysInService,
		BuyerCode,
		PDepreciationRate,
		PDepreciationPCT,
		TasModel,
		SubType,
		SaleDocumentNumber,
		ProgramCAP,
		ProgramAccumDepreciation,
		Reference
	
	)
	VALUES
	(
		@CompanyCode,
		@Serial,
		@AreaCode,
		@Unit,
		@UnitLastDigit,
		@Plate,
		@InvoiceStatus,
		@SalePrice,
		@CapitalCost,
		@Depreciation,
		@DepreciationRate,
		@DepreciationPCT,
		@BuyBackCap,
		@LessOr,
		@BaseAndOptions,
		@SaleType,
		@VehicleClass,
		@VehicleStatus,
		@SpecialProgramIndicator,
		@ManufacturerCode,
		@ModelYear,
		@ModelCode,
		@PaymentMethod,
		@InvoiceNumber,
		@DeliveryDate,
		@InServiceDate,
		@OutServiceDate,
		@SaleDate,
		@MSODate,
		@VehicleType,
		@PL,
		@Mileage,
		@DaysInService,
		@BuyerCode,
		@PDepreciationRate,
		@PDepreciationPCT,
		@TasModel,
		@SubType,
		@SaleDocumentNumber,
		@ProgramCAP,
		@ProgramAccumDepreciation,
		@Reference
	
	)

    
END