//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EFSS")]
        public string ApplicationName {
            get {
                return ((string)(this["ApplicationName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jmartinezpavon@hertz.com")]
        public string SupportEmailAddress {
            get {
                return ((string)(this["SupportEmailAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("itservicedesk@hertz.com")]
        public string ApplicationEmailAddress {
            get {
                return ((string)(this["ApplicationEmailAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2011")]
        public int ApplicationStartYear {
            get {
                return ((int)(this["ApplicationStartYear"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/hefs/")]
        public string ApplicationReportServerFolder {
            get {
                return ((string)(this["ApplicationReportServerFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("itservicedesk@hertz.com")]
        public string HelpDesk {
            get {
                return ((string)(this["HelpDesk"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hescfs05\\Finance\\Financial Operations\\Fleet Accounting\\Downloads\\Manual Invoice" +
            "s\\Serials.xlsx")]
        public string ManualInvoicesPath {
            get {
                return ((string)(this["ManualInvoicesPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hescfs05\\Finance\\Financial Operations\\Fleet Accounting\\Downloads\\Manual Invoice" +
            "s\\")]
        public string ManualInvoicesPathFolder {
            get {
                return ((string)(this["ManualInvoicesPathFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hescfs05\\Finance\\Financial Operations\\Fleet Accounting\\Downloads\\Fleet Cash\\Cas" +
            "h_Targets.xlsx")]
        public string FleetCashTargetPath {
            get {
                return ((string)(this["FleetCashTargetPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hescfs05\\Finance\\Financial Operations\\Fleet Accounting\\Downloads\\Fleet Cash\\")]
        public string FleetCashTargetPathFolder {
            get {
                return ((string)(this["FleetCashTargetPathFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvoiceUK")]
        public string InvoiceUK {
            get {
                return ((string)(this["InvoiceUK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvoiceBE")]
        public string InvoiceBE {
            get {
                return ((string)(this["InvoiceBE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvoiceSZ")]
        public string InvoiceSZ {
            get {
                return ((string)(this["InvoiceSZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvoiceGE")]
        public string InvoiceGE {
            get {
                return ((string)(this["InvoiceGE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvoiceNE")]
        public string InvoiceNE {
            get {
                return ((string)(this["InvoiceNE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvoiceFR")]
        public string InvoiceFR {
            get {
                return ((string)(this["InvoiceFR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvoiceLU")]
        public string InvoiceLU {
            get {
                return ((string)(this["InvoiceLU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvoiceSP")]
        public string InvoiceSP {
            get {
                return ((string)(this["InvoiceSP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvoiceIT")]
        public string InvoiceIT {
            get {
                return ((string)(this["InvoiceIT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hescfs05\\Finance\\Financial Operations\\Fleet Accounting\\Downloads\\Fleet Cash\\Cas" +
            "hTargets.xls")]
        public string FleetCashTargetPath97 {
            get {
                return ((string)(this["FleetCashTargetPath97"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReportFleetCash")]
        public string ReportFleetCashReport {
            get {
                return ((string)(this["ReportFleetCashReport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReportDashboard")]
        public string ReportDashboard {
            get {
                return ((string)(this["ReportDashboard"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hescfs05\\Finance\\Financial Operations\\Fleet Accounting\\Downloads\\Tax Files\\2013" +
            "0883247200038897[1].020811.NRC.1.DEV")]
        public string TaxFileSP {
            get {
                return ((string)(this["TaxFileSP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/App_Files/SendEmail.vbs")]
        public string EmailVBScript {
            get {
                return ((string)(this["EmailVBScript"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hescfs05\\Finance\\Financial Operations\\Fleet Accounting\\Downloads\\Tax Files\\MATR" +
            "ICULACIONES-IM PARA GFLOTA.xlsx")]
        public string MatriculationPath {
            get {
                return ((string)(this["MatriculationPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/App_Files/EmailAttachments/InvoicesExcel.xls")]
        public string AttachmentExcelPath {
            get {
                return ((string)(this["AttachmentExcelPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/App_Files/EmailAttachments/InvoicesPDF.pdf")]
        public string AttachmentPDFPath {
            get {
                return ((string)(this["AttachmentPDFPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvoiceNETransport")]
        public string InvoiceNETransport {
            get {
                return ((string)(this["InvoiceNETransport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/App_Files/EmailAttachments/InvoiceTransport.pdf")]
        public string AttacmentsNETransport {
            get {
                return ((string)(this["AttacmentsNETransport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/App_Files/EmailAttachments/")]
        public string EmailAttachmentsPath {
            get {
                return ((string)(this["EmailAttachmentsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvoicesExcel.xls")]
        public string FileNameExcelAttachment {
            get {
                return ((string)(this["FileNameExcelAttachment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvoicesPDF.pdf")]
        public string FileNamePDFAttachment {
            get {
                return ((string)(this["FileNamePDFAttachment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvoiceTransport.pdf")]
        public string FileNamePDFTransport {
            get {
                return ((string)(this["FileNamePDFTransport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hescfs05\\Finance\\Financial Operations\\Fleet Accounting\\Downloads\\FTP Client\\FTP" +
            "_Me.bat")]
        public string FTP_Filename {
            get {
                return ((string)(this["FTP_Filename"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FTP_Script.txt")]
        public string FTP_Script {
            get {
                return ((string)(this["FTP_Script"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hescfs05\\Finance\\Financial Operations\\Fleet Accounting\\Downloads\\FTP Client\\FTP" +
            "_Script.txt")]
        public string FTP_Script_FileName {
            get {
                return ((string)(this["FTP_Script_FileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hescfs05\\Finance\\Financial Operations\\Fleet Accounting\\Downloads\\FTP Client\\")]
        public string FTP_Path {
            get {
                return ((string)(this["FTP_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hescft02\\D$\\FleetVisionImport")]
        public string FTP_EFSS {
            get {
                return ((string)(this["FTP_EFSS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hescfs05\\Finance\\Financial Operations\\Fleet Accounting\\EFSS FTP Files\\Upload\\")]
        public string FTP_Files_Path {
            get {
                return ((string)(this["FTP_Files_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sales.txt")]
        public string SalesFileName {
            get {
                return ((string)(this["SalesFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Buyers.txt")]
        public string BuyersFileName {
            get {
                return ((string)(this["BuyersFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Models.txt")]
        public string ModelsFileName {
            get {
                return ((string)(this["ModelsFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dashboard.txt")]
        public string DashboardFileName {
            get {
                return ((string)(this["DashboardFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FleetDay.txt")]
        public string FleetDayFileName {
            get {
                return ((string)(this["FleetDayFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FleetMonth.txt")]
        public string FleetMonthFileName {
            get {
                return ((string)(this["FleetMonthFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YearAdds.txt")]
        public string YearAddsFileName {
            get {
                return ((string)(this["YearAddsFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DayAdds.txt")]
        public string DayAddsFileName {
            get {
                return ((string)(this["DayAddsFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YearDels.txt")]
        public string YearDelsFileName {
            get {
                return ((string)(this["YearDelsFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DayDels.txt")]
        public string DayDelsFileName {
            get {
                return ((string)(this["DayDelsFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hescft02\\FleetVisionImport\\")]
        public string FTPFolder {
            get {
                return ((string)(this["FTPFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hescrad2\\i$\\EuropeanFleetSalesSystem\\SSIS packages repository\\EFSS\\ImportSales." +
            "dtsx")]
        public string DTSSales {
            get {
                return ((string)(this["DTSSales"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CreditNotes.txt")]
        public string CreditNotesFileName {
            get {
                return ((string)(this["CreditNotesFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://radreports.hertz.com/ReportServer")]
        public string ReportServerRadReports {
            get {
                return ((string)(this["ReportServerRadReports"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/EFSS-Reports/")]
        public string ReportFolder {
            get {
                return ((string)(this["ReportFolder"]));
            }
        }
    }
}
